export const EXTERNAL_CATALOGS = [
    { id: 3, name: "AUDIO" },
    { id: 7, name: "HARDWARE -> MESIN ANTRIAN" },
    { id: 58, name: "HARDWARE -> KUNCI PENGAMAN LAPTOP" },
    { id: 45, name: "HARDWARE -> GATE PARKIR" },
    { id: 46, name: "HARDWARE -> AUDIO PUBLIK" },
    { id: 47, name: "HARDWARE -> KABEL (Power, LAN, VGA, dll)" },
    { id: 48, name: "HARDWARE -> BARCODE" },
    { id: 49, name: "HARDWARE -> CHARGER LAPTOP" },
    { id: 50, name: "HARDWARE -> WIFI" },
    { id: 51, name: "HARDWARE -> MICROPHONE" },
    { id: 52, name: "HARDWARE -> UPS" },
    { id: 53, name: "HARDWARE -> SWITCH HUB" },
    { id: 54, name: "HARDWARE -> SETTING ALAT IT, PERSIAPAN EVENT, PINDAHAN" },
    { id: 11, name: "HARDWARE -> CPU" },
    { id: 12, name: "HARDWARE -> MONITOR" },
    { id: 13, name: "HARDWARE -> KEYBOARD" },
    { id: 14, name: "HARDWARE -> MOUSE" },
    { id: 15, name: "HARDWARE -> PRINTER & SCANNER" },
    { id: 16, name: "HARDWARE -> LAPTOP" },
    { id: 17, name: "HARDWARE -> IPTV-SETUP BOX" },
    { id: 18, name: "HARDWARE -> TV DIGITAL" },
    { id: 19, name: "HARDWARE -> CCTV" },
    { id: 20, name: "HARDWARE -> FINGERPRINT" },
    { id: 21, name: "HARDWARE -> FINGER ACCESS" },
    { id: 22, name: "HARDWARE -> TELEPON" },
    { id: 23, name: "HARDWARE -> JARINGAN" },
    { id: 24, name: "HARDWARE -> IP PHONE" },
    { id: 25, name: "HARDWARE -> LAINNYA" },
    { id: 26, name: "SOFTWARE -> PATIENT INFO SYS (PIS)" },
    { id: 27, name: "SOFTWARE -> OM (LAB,RAD,OBAT,GIZI,LAUNDRY)" },
    { id: 29, name: "SOFTWARE -> MEDICAL RECORD, TRACKING & MANAGEMENT" },
    { id: 30, name: "SOFTWARE -> FINANCE & ACCOUNTING, FIXED ASSET" },
    { id: 31, name: "SOFTWARE -> MATERIAL MANAGEMENT" },
    { id: 32, name: "SOFTWARE -> HRD dan PARYOLL" },
    { id: 36, name: "SOFTWARE -> PHARMACY INFO SYS" },
    { id: 37, name: "SOFTWARE -> DIETARY & LAUNDRY" },
    { id: 38, name: "SOFTWARE -> LIS" },
    { id: 39, name: "SOFTWARE -> MAINTENANCE INFO SYS" },
    { id: 40, name: "SOFTWARE -> EXECUTIVE INFO SYS" },
    { id: 41, name: "SOFTWARE -> LAIN-LAIN" },
    { id: 55, name: "SOFTWARE -> INTERVENSI DATABASE" },
    { id: 56, name: "SOFTWARE -> OFFICE" },
    { id: 57, name: "SOFTWARE -> R M E" },
    { id: 59, name: "SOFTWARE -> KARIADI MOBILE" },
    { id: 60, name: "SOFTWARE -> APLIKASI BERBASIS WEB" },
    { id: 6, name: "VISUAL -> TV" },
    { id: 8, name: "PERANGKAT PENUNJANG -> PRINTER" },
    { id: 9, name: "PERANGKAT PENUNJANG -> FINGERSPOT" },
    { id: 43, name: "MAINTENANCE -> PC" },
    { id: 44, name: "MAINTENANCE -> SWITCH" }
];

export const EXTERNAL_USERS = [
    { id: 7, login: "dale", name: "DaleHabiby" },
    { id: 8, login: "dadi", name: "Dadi Susanto" },
    { id: 12, login: "agman", name: "agman" },
    { id: 13, login: "mek", name: "Mike Kumara Adhitama" },
    { id: 14, login: "guntur", name: "guntur pahlawan" },
    { id: 15, login: "trimardiati", name: "tri mardiati" },
    { id: 16, login: "cutmutia", name: "Cut mutia" },
    { id: 17, login: "rifki", name: "Rifki" },
    { id: 18, login: "nova", name: "Nova Oktaviani Hadinata" },
    { id: 20, login: "ken", name: "Ken Sutejo Widyantoro" },
    { id: 22, login: "dina", name: "Dina Fina Aulia" },
    { id: 23, login: null, name: "Adit Setiawan" },
    { id: 24, login: "joko", name: "Joko Wimpuno" },
    { id: 29, login: null, name: "Muhammad Hanif Zuhri" },
    { id: 31, login: "fitri", name: "Fitri Yuliasanti" },
    { id: 33, login: "arifin", name: "Arifin" },
    { id: 34, login: "adjisugiyanto", name: "Adji Sugiyanto" },
    { id: 35, login: null, name: "Adhi" },
    { id: 38, login: "iwan", name: "Iwan apriyanto" },
    { id: 39, login: "heru", name: "Heru Haryanto" },
    { id: 41, login: "yosep", name: "Yosep AW" },
    { id: 42, login: "lukman", name: "Lukman" },
    { id: 47, login: "mita", name: "Mita" },
    { id: 48, login: null, name: "Lanang Rizky" },
    { id: 49, login: "balam", name: "Balam Proyoga" },
    { id: 50, login: null, name: "Eruidf" },
    { id: 54, login: "triadi", name: "Tri Adi" },
    { id: 55, login: null, name: "Bella" },
    { id: 57, login: "donyk", name: "Dony K" },
    { id: 58, login: null, name: "Nino" },
    { id: 61, login: null, name: "Arditya Rama Saputra" },
    { id: 62, login: null, name: "Ardian Adi Saputra" },
    { id: 63, login: null, name: "Quvonch" },
    { id: 64, login: "nugrohochairul", name: "Nugroho Chairul Djati" },
    { id: 65, login: null, name: "Ahmad Joni Siswanto" },
    { id: 67, login: null, name: "Farizky Juniarto Pratama" },
    { id: 69, login: null, name: "Memey" },
    { id: 70, login: "ridwanrisky", name: "Ridwan Risky R" },
    { id: 71, login: "prihanantojoko", name: "Prihananto Joko TL" },
    { id: 73, login: "mhafidz", name: "Mohammad Hafidz" },
    { id: 74, login: "naditacandra", name: "Nadita Candra" },
    { id: 75, login: "edorizky", name: "Edo rizky saputro" },
    { id: 76, login: "mhuda", name: "Miftakhul Huda" },
    { id: 77, login: "alimuhtas", name: "ALI MUHTAS" },
    { id: 78, login: "ryanaffandi", name: "Ryan Affandi Saputra" },
    { id: 79, login: "johantaufik", name: "Johan Taufik" },
    { id: 80, login: "agusedy", name: "Agus Edy Cahyono" },
    { id: 81, login: "dessyannayumita", name: "Dessyanna Yumita Rachmawaty" },
    { id: 82, login: "afrizalrizqi", name: "Afrizal Rizqi Pranata" },
    { id: 83, login: "gilangheavy", name: "Gilang Heavy Pradana" },
    { id: 84, login: "agustadecky", name: "Agusta Decky Permana" },
    { id: 85, login: "arifjatmiko", name: "Arif Jatmiko" },
    { id: 86, login: "srihandayani", name: "Sri Handayani" },
    { id: 87, login: "tricahyani", name: "Tri cahyani atmojo" },
    { id: 89, login: "mokhammadiqbal", name: "Mokhammad Iqbal" },
    { id: 90, login: "wawan", name: "sulistyawan" },
    { id: 91, login: null, name: "Wawan" },
    { id: 92, login: null, name: "Caesar Kurnia Akbar" },
    { id: 93, login: null, name: "Anjas kusuma" },
    { id: 94, login: "adrianoyunas", name: "Adriano Yunas Supriyanto" }
];
