export const EXTERNAL_CATALOGS = [
    { id: 3, name: "AUDIO" },
    { id: 7, name: "HARDWARE -> MESIN ANTRIAN" },
    { id: 58, name: "HARDWARE -> KUNCI PENGAMAN LAPTOP" },
    { id: 45, name: "HARDWARE -> GATE PARKIR" },
    { id: 46, name: "HARDWARE -> AUDIO PUBLIK" },
    { id: 47, name: "HARDWARE -> KABEL (Power, LAN, VGA, dll)" },
    { id: 48, name: "HARDWARE -> BARCODE" },
    { id: 49, name: "HARDWARE -> CHARGER LAPTOP" },
    { id: 50, name: "HARDWARE -> WIFI" },
    { id: 51, name: "HARDWARE -> MICROPHONE" },
    { id: 52, name: "HARDWARE -> UPS" },
    { id: 53, name: "HARDWARE -> SWITCH HUB" },
    { id: 54, name: "HARDWARE -> SETTING ALAT IT, PERSIAPAN EVENT, PINDAHAN" },
    { id: 11, "name": "HARDWARE -> CPU" },
    { id: 12, "name": "HARDWARE -> MONITOR" },
    { id: 13, "name": "HARDWARE -> KEYBOARD" },
    { id: 14, "name": "HARDWARE -> MOUSE" },
    { id: 15, "name": "HARDWARE -> PRINTER & SCANNER" },
    { id: 16, "name": "HARDWARE -> LAPTOP" },
    { id: 17, "name": "HARDWARE -> IPTV-SETUP BOX" },
    { id: 18, "name": "HARDWARE -> TV DIGITAL" },
    { id: 19, "name": "HARDWARE -> CCTV" },
    { id: 20, "name": "HARDWARE -> FINGERPRINT" },
    { id: 21, "name": "HARDWARE -> FINGER ACCESS" },
    { id: 22, "name": "HARDWARE -> TELEPON" },
    { id: 23, "name": "HARDWARE -> JARINGAN" },
    { id: 24, "name": "HARDWARE -> IP PHONE" },
    { id: 25, "name": "HARDWARE -> LAINNYA" },
    { id: 26, "name": "SOFTWARE -> PATIENT INFO SYS (PIS)" },
    { id: 27, "name": "SOFTWARE -> OM (LAB,RAD,OBAT,GIZI,LAUNDRY)" },
    { id: 29, "name": "SOFTWARE -> MEDICAL RECORD, TRACKING & MANAGEMENT" },
    { id: 30, "name": "SOFTWARE -> FINANCE & ACCOUNTING, FIXED ASSET" },
    { id: 31, "name": "SOFTWARE -> MATERIAL MANAGEMENT" },
    { id: 32, "name": "SOFTWARE -> HRD dan PARYOLL" },
    { id: 36, "name": "SOFTWARE -> PHARMACY INFO SYS" },
    { id: 37, "name": "SOFTWARE -> DIETARY & LAUNDRY" },
    { id: 38, "name": "SOFTWARE -> LIS" },
    { id: 39, "name": "SOFTWARE -> MAINTENANCE INFO SYS" },
    { id: 40, "name": "SOFTWARE -> EXECUTIVE INFO SYS" },
    { id: 41, "name": "SOFTWARE -> LAIN-LAIN" },
    { id: 55, "name": "SOFTWARE -> INTERVENSI DATABASE" },
    { id: 56, "name": "SOFTWARE -> OFFICE" },
    { id: 57, "name": "SOFTWARE -> R M E" },
    { id: 59, "name": "SOFTWARE -> KARIADI MOBILE" },
    { id: 60, "name": "SOFTWARE -> APLIKASI BERBASIS WEB" },
    { id: 6, "name": "VISUAL -> TV" },
    { id: 8, "name": "PERANGKAT PENUNJANG -> PRINTER" },
    { id: 9, "name": "PERANGKAT PENUNJANG -> FINGERSPOT" },
    { id: 43, "name": "MAINTENANCE -> PC" },
    { id: 44, "name": "MAINTENANCE -> SWITCH" }
];

export const EXTERNAL_USERS = [
    { id: 7, name: "DaleHabiby" },
    { id: 8, name: "Dadi Susanto" },
    { id: 12, name: "agman" },
    { id: 13, name: "Mike Kumara Adhitama" },
    { id: 14, name: "guntur pahlawan" },
    { id: 15, name: "tri mardiati" },
    { id: 16, name: "Cut mutia" },
    { id: 17, name: "Rifki" },
    { id: 18, name: "Nova Oktaviani Hadinata" },
    { id: 20, "name": "Ken Sutejo Widyantoro" },
    { id: 22, "name": "Dina Fina Aulia" },
    { id: 23, "name": "Adit Setiawan" },
    { id: 24, "name": "Joko Wimpuno" },
    { id: 29, "name": "Muhammad Hanif Zuhri" },
    { id: 31, "name": "Fitri Yuliasanti" },
    { id: 33, "name": "Arifin" },
    { id: 34, "name": "Adji Sugiyanto" },
    { id: 35, "name": "Adhi" },
    { id: 38, "name": "Iwan apriyanto" },
    { id: 39, "name": "Heru Haryanto" },
    { id: 41, "name": "Yosep AW" },
    { id: 42, "name": "Lukman" },
    { id: 47, "name": "Mita" },
    { id: 48, "name": "Lanang Rizky" },
    { id: 49, "name": "Balam Proyoga" },
    { id: 50, "name": "Eruidf" },
    { id: 54, "name": "Tri Adi" },
    { id: 55, "name": "Bella" },
    { id: 57, "name": "Dony K" },
    { id: 58, "name": "Nino" },
    { id: 61, "name": "Arditya Rama Saputra" },
    { id: 62, "name": "Ardian Adi Saputra" },
    { id: 63, "name": "Quvonch" },
    { id: 64, "name": "Nugroho Chairul Djati" },
    { id: 65, "name": "Ahmad Joni Siswanto" },
    { id: 67, "name": "Farizky Juniarto Pratama" },
    { id: 69, "name": "Memey" },
    { id: 70, "name": "Ridwan Risky R" },
    { id: 71, "name": "Prihananto Joko TL" },
    { id: 73, "name": "Mohammad Hafidz" },
    { id: 74, "name": "Nadita Candra" },
    { id: 75, "name": "Edo rizky saputro" },
    { id: 76, "name": "Miftakhul Huda" },
    { id: 77, "name": "ALI MUHTAS" },
    { id: 78, "name": "Ryan Affandi Saputra" },
    { id: 79, "name": "Johan Taufik" },
    { id: 80, "name": "Agus Edy Cahyono" },
    { id: 81, "name": "Dessyanna Yumita Rachmawaty" },
    { id: 82, "name": "Afrizal Rizqi Pranata" },
    { id: 83, "name": "Gilang Heavy Pradana" },
    { id: 84, "name": "Agusta Decky Permana" },
    { id: 85, "name": "Arif Jatmiko" },
    { id: 86, "name": "Sri Handayani" },
    { id: 87, "name": "Tri cahyani atmojo" },
    { id: 89, "name": "Mokhammad Iqbal" },
    { id: 90, "name": "sulistyawan" },
    { id: 91, "name": "Wawan" },
    { id: 92, "name": "Caesar Kurnia Akbar" },
    { id: 93, "name": "Anjas kusuma" },
    { id: 94, "name": "Adriano Yunas Supriyanto" }
];
