export const EXTERNAL_CATALOGS = [
    { id: 3, name: "AUDIO" },
    { id: 7, name: "HARDWARE -> MESIN ANTRIAN" },
    { id: 58, name: "HARDWARE -> KUNCI PENGAMAN LAPTOP" },
    { id: 45, name: "HARDWARE -> GATE PARKIR" },
    { id: 46, name: "HARDWARE -> AUDIO PUBLIK" },
    { id: 47, name: "HARDWARE -> KABEL (Power, LAN, VGA, dll)" },
    { id: 48, name: "HARDWARE -> BARCODE" },
    { id: 49, name: "HARDWARE -> CHARGER LAPTOP" },
    { id: 50, name: "HARDWARE -> WIFI" },
    { id: 51, name: "HARDWARE -> MICROPHONE" },
    { id: 52, name: "HARDWARE -> UPS" },
    { id: 53, name: "HARDWARE -> SWITCH HUB" },
    { id: 54, name: "HARDWARE -> SETTING ALAT IT, PERSIAPAN EVENT, PINDAHAN" },
    { id: 11, name: "HARDWARE -> CPU" },
    { id: 12, name: "HARDWARE -> MONITOR" },
    { id: 13, name: "HARDWARE -> KEYBOARD" },
    { id: 14, name: "HARDWARE -> MOUSE" },
    { id: 15, name: "HARDWARE -> PRINTER & SCANNER" },
    { id: 16, name: "HARDWARE -> LAPTOP" },
    { id: 17, name: "HARDWARE -> IPTV-SETUP BOX" },
    { id: 18, name: "HARDWARE -> TV DIGITAL" },
    { id: 19, name: "HARDWARE -> CCTV" },
    { id: 20, name: "HARDWARE -> FINGERPRINT" },
    { id: 21, name: "HARDWARE -> FINGER ACCESS" },
    { id: 22, name: "HARDWARE -> TELEPON" },
    { id: 23, name: "HARDWARE -> JARINGAN" },
    { id: 24, name: "HARDWARE -> IP PHONE" },
    { id: 25, name: "HARDWARE -> LAINNYA" },
    { id: 26, name: "SOFTWARE -> PATIENT INFO SYS (PIS)" },
    { id: 27, name: "SOFTWARE -> OM (LAB,RAD,OBAT,GIZI,LAUNDRY)" },
    { id: 29, name: "SOFTWARE -> MEDICAL RECORD, TRACKING & MANAGEMENT" },
    { id: 30, name: "SOFTWARE -> FINANCE & ACCOUNTING, FIXED ASSET" },
    { id: 31, name: "SOFTWARE -> MATERIAL MANAGEMENT" },
    { id: 32, name: "SOFTWARE -> HRD dan PARYOLL" },
    { id: 36, name: "SOFTWARE -> PHARMACY INFO SYS" },
    { id: 37, name: "SOFTWARE -> DIETARY & LAUNDRY" },
    { id: 38, name: "SOFTWARE -> LIS" },
    { id: 39, name: "SOFTWARE -> MAINTENANCE INFO SYS" },
    { id: 40, name: "SOFTWARE -> EXECUTIVE INFO SYS" },
    { id: 41, name: "SOFTWARE -> LAIN-LAIN" },
    { id: 55, name: "SOFTWARE -> INTERVENSI DATABASE" },
    { id: 56, name: "SOFTWARE -> OFFICE" },
    { id: 57, name: "SOFTWARE -> R M E" },
    { id: 59, name: "SOFTWARE -> KARIADI MOBILE" },
    { id: 60, name: "SOFTWARE -> APLIKASI BERBASIS WEB" },
    { id: 6, name: "VISUAL -> TV" },
    { id: 8, name: "PERANGKAT PENUNJANG -> PRINTER" },
    { id: 9, name: "PERANGKAT PENUNJANG -> FINGERSPOT" },
    { id: 43, name: "MAINTENANCE -> PC" },
    { id: 44, name: "MAINTENANCE -> SWITCH" }
];


